### ISSUE TITLE
Ping button will not turn icon back to the off state if device goes offline

### ISSUE THREAD

**Issue by matt199x** [JakeJP/YokinsWOL#2]
If the button is green the ping button will not turn the button back to the off state if the device is no longer online. The ping button will work fine to turn the button green if the device turns on but it won't turn it back to grey if you click it when the device turns back off. 

Refreshing the page is a workaround.

**Comment by matt199x** [comment]
I changed line 199 in default.aspx

from
`buttons.removeClass("checking");`
to
`buttons.removeClass("checking").removeClass("green");`

It appears to be working fine now.

**Comment by JakeJP** [comment]
Thanks for your support.
